#!/usr/bin/env python3
"""Generate platform resource files from the shared string catalogue.

    shared/i18n/strings.json
        -> android/app/src/main/res/values[-<lang>]/strings.xml
        -> ios/TradesManager/Resources/<lang>.lproj/Localizable.strings
        -> ios/TradesManager/Resources/<lang>.lproj/Localizable.stringsdict
        -> ios/TradesManager/Resources/<lang>.lproj/InfoPlist.strings

Adding a language is a translation job, not a development job: add the
language code to "languages" in strings.json, add that key to every entry,
run this script, and register the code in the two places the guide lists
(docs/LOCALIZATION.md). No application source changes.

Run with --check to verify the generated files are current (used by CI).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import unicodedata
from xml.sax.saxutils import escape as xml_escape

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "shared" / "i18n" / "strings.json"
ANDROID_RES = ROOT / "android" / "app" / "src" / "main" / "res"
IOS_RES = ROOT / "ios" / "TradesManager" / "Resources"

# Store-facing permission strings. Both platforms must explain, in the user's
# language, why a permission is wanted: Apple reads these from InfoPlist.strings
# at review time, Android shows them in the app's own rationale screen.
IOS_INFO_PLIST_KEYS = {
    "NSCameraUsageDescription": "perm_camera_body",
    "NSPhotoLibraryUsageDescription": "perm_camera_body",
    "NSMicrophoneUsageDescription": "perm_mic_body",
    "NSSpeechRecognitionUsageDescription": "perm_mic_body",
    "NSLocationWhenInUseUsageDescription": "perm_location_body",
}

GENERATED_BANNER = "Generated by tools/gen-strings.py from shared/i18n/strings.json. Do not edit by hand."


def load() -> dict:
    with CATALOGUE.open(encoding="utf-8") as fh:
        return json.load(fh)


def validate(data: dict) -> list[str]:
    problems: list[str] = []
    languages = data["languages"]
    source = data["sourceLanguage"]
    if source not in languages:
        problems.append(f"sourceLanguage {source!r} is not listed in languages")
    for key, entry in data["strings"].items():
        for lang in languages:
            if not entry.get(lang):
                problems.append(f"strings.{key}: missing {lang}")
    for key, entry in data["plurals"].items():
        for lang in languages:
            forms = entry.get(lang)
            if not forms:
                problems.append(f"plurals.{key}: missing {lang}")
            elif "other" not in forms:
                problems.append(f"plurals.{key}.{lang}: no 'other' form")
    for key in IOS_INFO_PLIST_KEYS.values():
        if key not in data["strings"]:
            problems.append(f"InfoPlist mapping references unknown key {key!r}")
    return problems


def android_escape(text: str) -> str:
    """Android string resource escaping (apostrophes and quotes are literal)."""
    out = xml_escape(text)
    out = out.replace("'", r"\'").replace('"', r"\"")
    if out[:1] in ("@", "?"):
        out = "\\" + out
    return out


def ios_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def android_values_dir(lang: str, source: str) -> pathlib.Path:
    return ANDROID_RES / ("values" if lang == source else f"values-{lang}")


def render_android(data: dict, lang: str) -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {GENERATED_BANNER} -->", "<resources>"]
    for key, entry in data["strings"].items():
        comment = entry.get("c")
        if comment and lang == data["sourceLanguage"]:
            lines.append(f"    <!-- {xml_escape(comment)} -->")
        lines.append(f'    <string name="{key}">{android_escape(entry[lang])}</string>')
    for key, entry in data["plurals"].items():
        lines.append(f'    <plurals name="{key}">')
        for quantity, text in entry[lang].items():
            lines.append(f'        <item quantity="{quantity}">{android_escape(text)}</item>')
        lines.append("    </plurals>")
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def render_ios_strings(data: dict, lang: str) -> str:
    lines = [f"/* {GENERATED_BANNER} */", ""]
    for key, entry in data["strings"].items():
        comment = entry.get("c")
        if comment:
            lines.append(f"/* {comment} */")
        lines.append(f'"{key}" = "{ios_escape(entry[lang])}";')
    return "\n".join(lines) + "\n"


def render_ios_stringsdict(data: dict, lang: str) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {GENERATED_BANNER} -->",
        '<plist version="1.0">',
        "<dict>",
    ]
    for key, entry in data["plurals"].items():
        lines += [
            f"    <key>{key}</key>",
            "    <dict>",
            "        <key>NSStringLocalizedFormatKey</key>",
            "        <string>%#@count@</string>",
            "        <key>count</key>",
            "        <dict>",
            "            <key>NSStringFormatSpecTypeKey</key>",
            "            <string>NSStringPluralRuleType</string>",
            "            <key>NSStringFormatValueTypeKey</key>",
            "            <string>d</string>",
        ]
        for quantity, text in entry[lang].items():
            lines.append(f"            <key>{quantity}</key>")
            lines.append(f"            <string>{xml_escape(text)}</string>")
        lines += ["        </dict>", "    </dict>"]
    lines += ["</dict>", "</plist>"]
    return "\n".join(lines) + "\n"


def render_ios_infoplist(data: dict, lang: str) -> str:
    lines = [f"/* {GENERATED_BANNER} */", ""]
    for plist_key, string_key in IOS_INFO_PLIST_KEYS.items():
        lines.append(f'"{plist_key}" = "{ios_escape(data["strings"][string_key][lang])}";')
    return "\n".join(lines) + "\n"


def write(path: pathlib.Path, content: str, check: bool, stale: list[str]) -> None:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(str(path.relative_to(ROOT)))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    data = load()
    problems = validate(data)
    if problems:
        print("Translation catalogue is incomplete:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    stale: list[str] = []
    for lang in data["languages"]:
        write(android_values_dir(lang, data["sourceLanguage"]) / "strings.xml",
              render_android(data, lang), args.check, stale)
        lproj = IOS_RES / f"{lang}.lproj"
        write(lproj / "Localizable.strings", render_ios_strings(data, lang), args.check, stale)
        write(lproj / "Localizable.stringsdict", render_ios_stringsdict(data, lang), args.check, stale)
        write(lproj / "InfoPlist.strings", render_ios_infoplist(data, lang), args.check, stale)

    if args.check:
        if stale:
            print("These generated files are out of date — run tools/gen-strings.py:", file=sys.stderr)
            for path in stale:
                print(f"  - {path}", file=sys.stderr)
            return 1
        print("Generated string resources are up to date.")
        return 0

    rtl = [lang for lang in data["languages"]
           if unicodedata.bidirectional(data["strings"]["app_name"][lang][0]) in ("R", "AL")]
    print(f"Wrote resources for {len(data['languages'])} languages "
          f"({len(data['strings'])} strings, {len(data['plurals'])} plurals).")
    print(f"Right-to-left languages detected: {', '.join(rtl) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
